In [ ]:
print("Hello my name is Ario")

In [ ]:
!nvidia-smi

In [ ]:
import torch
print(torch.__version__)

Creating Tensors

In [ ]:
scalar = torch.tensor(7)
scalar

In [ ]:
scalar.ndim

In [ ]:
# get tensor back as python int
scalar.item()

In [ ]:
# vector
vector = torch.tensor([7,7])
vector

In [ ]:
vector.ndim

In [ ]:
vector.shape

In [99]:
# matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [100]:
MATRIX.ndim

2

In [101]:
# tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[10, 10, 320],
                        [83, 5, 64],
                        [49, 7, 34]]])
TENSOR

tensor([[[  1,   2,   3],
         [  3,   6,   9],
         [  2,   4,   5]],

        [[  1,   2,   3],
         [  4,   5,   6],
         [  7,   8,   9]],

        [[ 10,  10, 320],
         [ 83,   5,  64],
         [ 49,   7,  34]]])

In [102]:
TENSOR.ndim

3

In [103]:
TENSOR.shape

torch.Size([3, 3, 3])

In [104]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [105]:
TENSOR[1]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [106]:
TENSOR[2]

tensor([[ 10,  10, 320],
        [ 83,   5,  64],
        [ 49,   7,  34]])

In [107]:
TENSOR[0][0]

tensor([1, 2, 3])

In [108]:
TENSOR[2][1]

tensor([83,  5, 64])

### Random tensors
random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.


`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers
`

In [109]:
# create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7112, 0.8207, 0.4910, 0.4770],
        [0.4832, 0.1177, 0.6367, 0.1776],
        [0.4313, 0.8647, 0.9616, 0.3707]])

In [110]:
random_tensor.ndim

2

In [111]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [112]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [113]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [114]:
# Create tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [115]:
ones.dtype

torch.float32

In [116]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [117]:
# Use torch.range()
torch.range(0, 10)

/tmp/ipykernel_1144/1840815090.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [118]:
# Since torch.range() is deprecated, we use torch.arange()
one_to_ten = torch.arange(start=1, step=1, end=11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

*   Sinlge percision: 32-bit float (default)
*   half percision: 16-bit float
*   doule percision: 64-bit float

**Lower percision is faster but less precise and higher percision is vice versa.**


**Note:** Tensor datatypes is one fo the 3 big errors you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors nto on the right device

In [120]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (float32 or float 16)
                               device=None, # what device the tensor is on. "cpu" or "cuda" (cuda: using nvidia gpu)
                               requires_grad=False # whether or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [121]:
float_32_tensor.dtype

torch.float32

In [122]:
# Float 16 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
# OR
float_16_tensor = float_32_tensor.type(torch.float16)
# OR
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [123]:
float_16_tensor.dtype

torch.float16

In [124]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [125]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [126]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)
1. Tensors not right datatype - to get datatype from a tesor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [127]:
some_tensor = torch.rand(size=(3, 4))
some_tensor

tensor([[0.0154, 0.8271, 0.4540, 0.4044],
        [0.6473, 0.3085, 0.7872, 0.8996],
        [0.9211, 0.6327, 0.0263, 0.3109]])

`some_tensor.shape()` returns the exact same response as `some_tensor.shape`

(one is a method and the other is an attribute)

In [128]:
# Find out details about some tensor
print(some_tensor, end="\n\n")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0154, 0.8271, 0.4540, 0.4044],
        [0.6473, 0.3085, 0.7872, 0.8996],
        [0.9211, 0.6327, 0.0263, 0.3109]])

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operation)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [129]:
# Create a tensor and add 10 to it
TENSOR = torch.tensor([1, 2, 3])

In [130]:
%%time
TENSOR + 10

CPU times: user 498 µs, sys: 0 ns, total: 498 µs
Wall time: 417 µs


tensor([11, 12, 13])

In [131]:
# Multiply tensor by 10
%%time
TENSOR * 10

CPU times: user 329 µs, sys: 37 µs, total: 366 µs
Wall time: 681 µs


tensor([10, 20, 30])

In [132]:
# Subtract 10
TENSOR - 10

tensor([-9, -8, -7])

In [133]:
# Try out PyTorch in-built functions
%%time
torch.mul(TENSOR, 10)

CPU times: user 23 µs, sys: 1.01 ms, total: 1.04 ms
Wall time: 936 µs


tensor([10, 20, 30])

In [134]:
%%time
torch.add(TENSOR, 10)

CPU times: user 319 µs, sys: 38 µs, total: 357 µs
Wall time: 327 µs


tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3,2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimension**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [135]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [136]:
first = torch.rand(2, 3)
first

tensor([[0.3394, 0.5309, 0.5349],
        [0.6045, 0.5853, 0.8468]])

In [137]:
second =torch.rand(3, 2)
second

tensor([[0.7702, 0.6400],
        [0.3796, 0.7514],
        [0.8115, 0.6831]])

In [138]:
torch.matmul(first, second)

tensor([[0.8970, 0.9815],
        [1.3750, 1.4052]])

In [139]:
# Element-wise multiplication
print(TENSOR, "*", TENSOR)
print(f"Equals: {TENSOR * TENSOR}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [140]:
# Matrix multiplication
torch.matmul(TENSOR, TENSOR)
# OR
# torch.mm(TENSOR, TENSOR)
# BUT torch.mm() does NOT tolerate dimensionality issue which would return an error on single-dimentional matrices

tensor(14)

In [141]:
TENSOR

tensor([1, 2, 3])

In [142]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [143]:
# @ has the same functionality as torch.matmul() but torch.matmul() is recommended
TENSOR @ TENSOR

tensor(14)

In [144]:
%%time
value = 0
for i in range(len(TENSOR)):
  value += TENSOR[i] * TENSOR[i]
value

CPU times: user 550 µs, sys: 0 ns, total: 550 µs
Wall time: 557 µs


tensor(14)

In [145]:
%%time
torch.matmul(TENSOR, TENSOR)

CPU times: user 74 µs, sys: 0 ns, total: 74 µs
Wall time: 77.2 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [146]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches axes or diensions of a given tensor

it is used as: `myTensor.T`

In [147]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [148]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [149]:
# The matrix multipliatin opreation works when tensor_B is transposed
print(f"Original shapes:\ntensor_A = {tensor_A.shape},\ntensor_B = {tensor_B.shape}")
print(f"\nNew shapes:\ntensor_A = {tensor_A.shape} (same shape as the above),\ntensor_B.T = {tensor_B.T.shape}")
print(f"\nMultiplying:\n{tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes:
tensor_A = torch.Size([3, 2]),
tensor_B = torch.Size([3, 2])

New shapes:
tensor_A = torch.Size([3, 2]) (same shape as the above),
tensor_B.T = torch.Size([2, 3])

Multiplying:
torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding min, max, mean, sum, etc (tensor aggregation)

In [150]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [151]:
#Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [152]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [153]:
# Find th mean
# our x is in type int64 so we have to change it for it to work with the "mean()" function
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [154]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [155]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [156]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of the minimum value
x.argmin()

tensor(0)

In [157]:
x[0]

tensor(0)

In [158]:
# Find the position in tensor that has the maximum value with argmax() -> returns index position of the maximum value
x.argmax()

tensor(9)

In [159]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing, and unsqeezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [196]:
# Create a tensor
import torch
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [198]:
# Add an extra dimension
# The number of rows times the number of columns must be equal to the total number of elements we have for the reshape method to work.
x_reshaped = x.reshape(1, 12)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]),
 2)

In [199]:
x_reshaped2 = x.reshape(12, 1)
x_reshaped2, x_reshaped2.shape, x_reshaped2.ndim

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.]]),
 torch.Size([12, 1]),
 2)

In [200]:
x_reshaped3 = x.reshape(3, 4)
x_reshaped3, x_reshaped3.shape, x_reshaped.ndim

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]),
 2)

In [201]:
# Changing the "view"
z = x.view(1, 12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [202]:
# Changing z changes x because a view of a tensor shares the same memory location as the original input
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [203]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # dim=0 is horizontal, dim=1 is vertical, and so on (depending on how many dimensions our tensor has)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [204]:
x_stacked2 = torch.stack([x, x, x, x], dim=1)
x_stacked2

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [205]:
# torch.squeeze() - removes all single dimensions from a target tensor
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [206]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [207]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [208]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [209]:
y = torch.squeeze(x, (1, 2, 3))
y.size()

torch.Size([2, 2, 2])

In [210]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
Previous shape: torch.Size([1, 12])

New tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
New shape: torch.Size([12])


In [211]:
# torch.unsqueeze() - adds a asingle dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
Previous shape: torch.Size([12])

New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
New shape: torch.Size([1, 12])


In [212]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
z = torch.randn(2, 3, 5)
print(f"Previous size: {z.size()}")
z_permuted = torch.permute(z, (2, 0, 1)).size() # rearranges the dimensions based on index
print(f"\nNew size: {z_permuted}")

Previous size: torch.Size([2, 3, 5])

New size: torch.Size([5, 2, 3])


In [213]:
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)
# shifts:
# 2 -> 0
# 0 -> 1
# 1 -> 2

print(f"Previous shape: {x_original.shape}") # [height, width, color_channel]
print(f"New shape:      {x_permuted.shape}") # [color_channel, height, width]


Previous shape: torch.Size([224, 224, 3])
New shape:      torch.Size([3, 224, 224])


In [214]:
x_original[:, 0, 0], x_permuted[:, 0, 0]

(tensor([9.6819e-01, 8.1718e-01, 1.4839e-01, 5.8951e-02, 6.3851e-01, 8.5572e-02,
         5.1055e-01, 3.4608e-01, 8.2961e-02, 9.4171e-01, 6.1502e-01, 1.2928e-01,
         7.4380e-01, 1.8535e-01, 5.0466e-01, 7.6752e-01, 3.2441e-01, 6.1440e-01,
         2.2441e-01, 2.4688e-01, 6.1666e-01, 8.7930e-01, 1.0104e-01, 3.9320e-02,
         2.3770e-01, 6.6536e-01, 8.2203e-01, 6.5173e-01, 8.3904e-01, 2.4383e-01,
         5.3686e-01, 3.7548e-01, 4.1574e-01, 7.3446e-01, 1.4834e-01, 5.2119e-01,
         5.3894e-01, 1.3208e-01, 8.1038e-01, 4.3719e-01, 6.7216e-01, 3.4407e-01,
         1.3453e-01, 1.0855e-01, 3.3429e-01, 9.3892e-01, 6.5114e-01, 4.4879e-01,
         3.6517e-02, 2.2950e-02, 1.4946e-01, 3.4243e-01, 9.9251e-01, 5.9001e-01,
         3.4763e-01, 9.3094e-01, 4.5005e-01, 8.7187e-01, 7.3999e-01, 6.1556e-01,
         2.5314e-04, 7.7966e-01, 1.3435e-02, 4.6213e-02, 7.0553e-01, 8.0125e-01,
         3.4225e-01, 1.3306e-01, 2.5011e-01, 2.0800e-01, 2.8181e-01, 8.3900e-01,
         2.1184e-01, 9.6335e

In [215]:
x_original[0, 0, 0] = 2
x_permuted[0, 0, 0]

tensor(2.)

In [216]:
test = torch.tensor([[[1, 2], [1, 2], [1, 2], [1, 2]],
                     [[3, 4], [3, 4], [3, 4], [3, 4]],
                     [[5, 6], [5, 6], [5, 6], [5, 6]],
                     [[7, 8], [7, 8], [7, 8], [7, 8]]])

In [217]:
test_permuted = torch.permute(test, (2, 0, 1))
test, test_permuted

(tensor([[[1, 2],
          [1, 2],
          [1, 2],
          [1, 2]],
 
         [[3, 4],
          [3, 4],
          [3, 4],
          [3, 4]],
 
         [[5, 6],
          [5, 6],
          [5, 6],
          [5, 6]],
 
         [[7, 8],
          [7, 8],
          [7, 8],
          [7, 8]]]),
 tensor([[[1, 1, 1, 1],
          [3, 3, 3, 3],
          [5, 5, 5, 5],
          [7, 7, 7, 7]],
 
         [[2, 2, 2, 2],
          [4, 4, 4, 4],
          [6, 6, 6, 6],
          [8, 8, 8, 8]]]))

In [218]:
test[0, 0, 0] = 23
test, test_permuted

(tensor([[[23,  2],
          [ 1,  2],
          [ 1,  2],
          [ 1,  2]],
 
         [[ 3,  4],
          [ 3,  4],
          [ 3,  4],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 5,  6],
          [ 5,  6],
          [ 5,  6]],
 
         [[ 7,  8],
          [ 7,  8],
          [ 7,  8],
          [ 7,  8]]]),
 tensor([[[23,  1,  1,  1],
          [ 3,  3,  3,  3],
          [ 5,  5,  5,  5],
          [ 7,  7,  7,  7]],
 
         [[ 2,  2,  2,  2],
          [ 4,  4,  4,  4],
          [ 6,  6,  6,  6],
          [ 8,  8,  8,  8]]]))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [219]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [220]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [221]:
# let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [222]:
# let's index on the most inner bracket (last dim)
x[0][0][0]

tensor(1)

In [223]:
# You can use ":" to select all of a target dimension
x[:][0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [224]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [225]:
# Get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [226]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [227]:
# Index on x to return 9
x[0,2,2]

tensor(9)

In [228]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.
* Parsing data from NumPy to PyTorch tensor -> `torch.from_numpy(ndarray)`
* Parsing data from PyTorch tensor to Numpy -> `torch.Tensor.numpy()`

In [234]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
# The default NumPy datatype is float64, and pytorch reflects numpy's default unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [235]:
# PyTorch by default creates tensors in float32
torch.arange(1.0, 8.0).dtype

torch.float32

In [236]:
# We can force the datatype for pytorch like the following
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype

torch.float32

In [238]:
# Change the value of array, what will happen to the tensor?
array = array + 1
array, tensor
# tensor is a new memory location so changing the numpy array won't affect the tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [239]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [240]:
# the tensor's datatype is taken by numpy array.
numpy_tensor.dtype

dtype('float32')

In [241]:
# Change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)
In short how a neural network learns:

`start with random numbers`
->
`tensor operations`
->
`update random numbers to try and make them better representations of the data`
->
`again` -> `again` -> `again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavor" the randomness.

In [244]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7169, 0.2865, 0.0750, 0.2161],
        [0.0760, 0.6935, 0.4573, 0.7107],
        [0.9153, 0.4591, 0.4550, 0.2611]])
tensor([[0.5210, 0.8636, 0.4064, 0.6135],
        [0.7971, 0.3514, 0.1172, 0.1521],
        [0.7226, 0.2006, 0.4526, 0.6217]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [246]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [249]:
# TRY SETTING MANUAL SEED EACH TIME
torch.manual_seed(RANDOM_SEED) # should use this line every time
random_tensor_E = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_F = torch.rand(3, 4)

print(random_tensor_E)
print(random_tensor_F)
print(random_tensor_E == random_tensor_F)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:

* https://docs.pytorch.org/docs/2.13/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed