In [1]:
print("Hello my name is Ario")

Hello my name is Ario


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
print(torch.__version__)

2.11.0+cpu


Creating Tensors

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# get tensor back as python int
scalar.item()

7

In [7]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
# tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[10, 10, 320],
                        [83, 5, 64],
                        [49, 7, 34]]])
TENSOR

tensor([[[  1,   2,   3],
         [  3,   6,   9],
         [  2,   4,   5]],

        [[  1,   2,   3],
         [  4,   5,   6],
         [  7,   8,   9]],

        [[ 10,  10, 320],
         [ 83,   5,  64],
         [ 49,   7,  34]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([3, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [16]:
TENSOR[1]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR[2]

tensor([[ 10,  10, 320],
        [ 83,   5,  64],
        [ 49,   7,  34]])

In [18]:
TENSOR[0][0]

tensor([1, 2, 3])

In [19]:
TENSOR[2][1]

tensor([83,  5, 64])

### Random tensors
random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.


`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers
`

In [20]:
# create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4970, 0.3846, 0.1283, 0.8666],
        [0.7806, 0.1522, 0.0868, 0.8651],
        [0.5125, 0.6360, 0.3514, 0.5691]])

In [21]:
random_tensor.ndim

2

In [22]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [23]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Create tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

In [27]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [28]:
# Use torch.range()
torch.range(0, 10)

/tmp/ipykernel_3273/1840815090.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
# Since torch.range() is deprecated, we use torch.arange()
one_to_ten = torch.arange(start=1, step=1, end=11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

*   Sinlge percision: 32-bit float (default)
*   half percision: 16-bit float
*   doule percision: 64-bit float

**Lower percision is faster but less precise and higher percision is vice versa.**


**Note:** Tensor datatypes is one fo the 3 big errors you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors nto on the right device

In [31]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (float32 or float 16)
                               device=None, # what device the tensor is on. "cpu" or "cuda" (cuda: using nvidia gpu)
                               requires_grad=False # whether or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [32]:
float_32_tensor.dtype

torch.float32

In [33]:
# Float 16 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
# OR
float_16_tensor = float_32_tensor.type(torch.float16)
# OR
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
float_16_tensor.dtype

torch.float16

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)
1. Tensors not right datatype - to get datatype from a tesor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [38]:
some_tensor = torch.rand(size=(3, 4))
some_tensor

tensor([[0.7688, 0.6749, 0.8078, 0.3731],
        [0.9917, 0.9119, 0.7355, 0.2108],
        [0.5990, 0.0192, 0.1839, 0.5509]])

`some_tensor.shape()` returns the exact same response as `some_tensor.shape`

(one is a method and the other is an attribute)

In [39]:
# Find out details about some tensor
print(some_tensor, end="\n\n")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7688, 0.6749, 0.8078, 0.3731],
        [0.9917, 0.9119, 0.7355, 0.2108],
        [0.5990, 0.0192, 0.1839, 0.5509]])

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operation)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [123]:
# Create a tensor and add 10 to it
TENSOR = torch.tensor([1, 2, 3])

In [124]:
%%time
TENSOR + 10

CPU times: user 288 µs, sys: 32 µs, total: 320 µs
Wall time: 282 µs


tensor([11, 12, 13])

In [125]:
# Multiply tensor by 10
%%time
TENSOR * 10

CPU times: user 295 µs, sys: 0 ns, total: 295 µs
Wall time: 265 µs


tensor([10, 20, 30])

In [126]:
# Subtract 10
TENSOR - 10

tensor([-9, -8, -7])

In [127]:
# Try out PyTorch in-built functions
%%time
torch.mul(TENSOR, 10)

CPU times: user 584 µs, sys: 0 ns, total: 584 µs
Wall time: 506 µs


tensor([10, 20, 30])

In [129]:
%%time
torch.add(TENSOR, 10)

CPU times: user 177 µs, sys: 0 ns, total: 177 µs
Wall time: 141 µs


tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3,2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimension**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [46]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [48]:
first = torch.rand(2, 3)
first

tensor([[0.2823, 0.0399, 0.9585],
        [0.0209, 0.2837, 0.9517]])

In [49]:
second =torch.rand(3, 2)
second

tensor([[0.4817, 0.6095],
        [0.0493, 0.6223],
        [0.6851, 0.0189]])

In [50]:
torch.matmul(first, second)

tensor([[0.7946, 0.2149],
        [0.6762, 0.2072]])

In [51]:
# Element-wise multiplication
print(TENSOR, "*", TENSOR)
print(f"Equals: {TENSOR * TENSOR}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [52]:
# Matrix multiplication
torch.matmul(TENSOR, TENSOR)
# OR
# torch.mm(TENSOR, TENSOR)
# BUT torch.mm() does NOT tolerate dimensionality issue which would return an error on single-dimentional matrices

tensor(14)

In [53]:
TENSOR

tensor([1, 2, 3])

In [54]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [55]:
# @ has the same functionality as torch.matmul() but torch.matmul() is recommended
TENSOR @ TENSOR

tensor(14)

In [56]:
%%time
value = 0
for i in range(len(TENSOR)):
  value += TENSOR[i] * TENSOR[i]
value

CPU times: user 1.13 ms, sys: 0 ns, total: 1.13 ms
Wall time: 3.62 ms


tensor(14)

In [57]:
%%time
torch.matmul(TENSOR, TENSOR)

CPU times: user 0 ns, sys: 668 µs, total: 668 µs
Wall time: 517 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [58]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches axes or diensions of a given tensor

it is used as: `myTensor.T`

In [59]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [60]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [61]:
# The matrix multipliatin opreation works when tensor_B is transposed
print(f"Original shapes:\ntensor_A = {tensor_A.shape},\ntensor_B = {tensor_B.shape}")
print(f"\nNew shapes:\ntensor_A = {tensor_A.shape} (same shape as the above),\ntensor_B.T = {tensor_B.T.shape}")
print(f"\nMultiplying:\n{tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes:
tensor_A = torch.Size([3, 2]),
tensor_B = torch.Size([3, 2])

New shapes:
tensor_A = torch.Size([3, 2]) (same shape as the above),
tensor_B.T = torch.Size([2, 3])

Multiplying:
torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding min, max, mean, sum, etc (tensor aggregation)

In [62]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
#Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [64]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [65]:
# Find th mean
# our x is in type int64 so we have to change it for it to work with the "mean()" function
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [66]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [67]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [68]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of the minimum value
x.argmin()

tensor(0)

In [69]:
x[0]

tensor(0)

In [70]:
# Find the position in tensor that has the maximum value with argmax() -> returns index position of the maximum value
x.argmax()

tensor(9)

In [71]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing, and unsqeezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [72]:
# Create a tensor
import torch
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [73]:
# Add an extra dimension
# The number of rows times the number of columns must be equal to the total number of elements we have for the reshape method to work.
x_reshaped = x.reshape(1, 12)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]),
 2)

In [74]:
x_reshaped2 = x.reshape(12, 1)
x_reshaped2, x_reshaped2.shape, x_reshaped2.ndim

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.]]),
 torch.Size([12, 1]),
 2)

In [75]:
x_reshaped3 = x.reshape(3, 4)
x_reshaped3, x_reshaped3.shape, x_reshaped.ndim

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]),
 2)

In [130]:
# Changing the "view"
z = x.view(1, 12)
z, z.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [131]:
# Changing z changes x because a view of a tensor shares the same memory location as the original input
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [132]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # dim=0 is horizontal, dim=1 is vertical, and so on (depending on how many dimensions our tensor has)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [134]:
x_stacked2 = torch.stack([x, x, x, x], dim=1)
x_stacked2

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [146]:
# torch.squeeze() - removes all single dimensions from a target tensor
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [147]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [148]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [149]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [151]:
y = torch.squeeze(x, (1, 2, 3))
y.size()

torch.Size([2, 2, 2])

In [155]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
Previous shape: torch.Size([1, 12])

New tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
New shape: torch.Size([12])


In [159]:
# torch.unsqueeze() - adds a asingle dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
Previous shape: torch.Size([12])

New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
New shape: torch.Size([1, 12])


In [163]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
z = torch.randn(2, 3, 5)
print(f"Previous size: {z.size()}")
z_permuted = torch.permute(x, (2, 0, 1)).size() # rearranges the dimensions based on index
print(f"\nNew size: {z_permuted}")

Previous size: torch.Size([2, 3, 5])

New size: torch.Size([5, 2, 3])


In [188]:
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)
# shifts:
# 2 -> 0
# 0 -> 1
# 1 -> 2

print(f"Previous shape: {x_original.shape}") # [height, width, color_channel]
print(f"New shape:      {x_permuted.shape}") # [color_channel, height, width]


Previous shape: torch.Size([224, 224, 3])
New shape:      torch.Size([3, 224, 224])


In [189]:
x_original[:, 0, 0], x_permuted[:, 0, 0]

(tensor([0.7456, 0.4491, 0.4904, 0.4966, 0.9153, 0.5635, 0.7103, 0.8450, 0.1915,
         0.7921, 0.1079, 0.8812, 0.7684, 0.0825, 0.7846, 0.7198, 0.3108, 0.0684,
         0.8113, 0.0858, 0.2148, 0.6286, 0.5915, 0.4297, 0.2979, 0.4919, 0.8221,
         0.3015, 0.9084, 0.4489, 0.6371, 0.4246, 0.0940, 0.8865, 0.5646, 0.7810,
         0.5228, 0.6923, 0.1728, 0.4430, 0.5794, 0.5747, 0.3548, 0.0884, 0.1773,
         0.0398, 0.1944, 0.3795, 0.2350, 0.5619, 0.7891, 0.0651, 0.7097, 0.9165,
         0.9697, 0.2921, 0.6228, 0.0895, 0.8047, 0.3162, 0.5485, 0.9059, 0.0910,
         0.6123, 0.0268, 0.5920, 0.8798, 0.0415, 0.7796, 0.7290, 0.9171, 0.7175,
         0.3789, 0.0839, 0.8609, 0.7820, 0.2098, 0.8082, 0.8516, 0.1451, 0.3836,
         0.3905, 0.8103, 0.5214, 0.6705, 0.9413, 0.4291, 0.3462, 0.6037, 0.6373,
         0.4302, 0.2986, 0.7316, 0.6094, 0.2480, 0.5513, 0.6709, 0.7689, 0.3226,
         0.1351, 0.6141, 0.4761, 0.3008, 0.4459, 0.5726, 0.7480, 0.0302, 0.4647,
         0.3260, 0.3235, 1.0

In [213]:
x_original[0, 0, 0] = 2
x_permuted[0, 0, 0]

tensor(2.)

In [214]:
test = torch.tensor([[[1, 2], [1, 2], [1, 2], [1, 2]],
                     [[3, 4], [3, 4], [3, 4], [3, 4]],
                     [[5, 6], [5, 6], [5, 6], [5, 6]],
                     [[7, 8], [7, 8], [7, 8], [7, 8]]])

In [215]:
test_permuted = torch.permute(test, (2, 0, 1))
test, test_permuted

(tensor([[[1, 2],
          [1, 2],
          [1, 2],
          [1, 2]],
 
         [[3, 4],
          [3, 4],
          [3, 4],
          [3, 4]],
 
         [[5, 6],
          [5, 6],
          [5, 6],
          [5, 6]],
 
         [[7, 8],
          [7, 8],
          [7, 8],
          [7, 8]]]),
 tensor([[[1, 1, 1, 1],
          [3, 3, 3, 3],
          [5, 5, 5, 5],
          [7, 7, 7, 7]],
 
         [[2, 2, 2, 2],
          [4, 4, 4, 4],
          [6, 6, 6, 6],
          [8, 8, 8, 8]]]))

In [216]:
test[0, 0, 0] = 23
test, test_permuted

(tensor([[[23,  2],
          [ 1,  2],
          [ 1,  2],
          [ 1,  2]],
 
         [[ 3,  4],
          [ 3,  4],
          [ 3,  4],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 5,  6],
          [ 5,  6],
          [ 5,  6]],
 
         [[ 7,  8],
          [ 7,  8],
          [ 7,  8],
          [ 7,  8]]]),
 tensor([[[23,  1,  1,  1],
          [ 3,  3,  3,  3],
          [ 5,  5,  5,  5],
          [ 7,  7,  7,  7]],
 
         [[ 2,  2,  2,  2],
          [ 4,  4,  4,  4],
          [ 6,  6,  6,  6],
          [ 8,  8,  8,  8]]]))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [232]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [233]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [234]:
# let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [235]:
# let's index on the most inner bracket (last dim)
x[0][0][0]

tensor(1)

In [236]:
# You can use ":" to select all of a target dimension
x[:][0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [242]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [246]:
# Get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [247]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [248]:
# Index on x to return 9
x[0,2,2]

tensor(9)

In [249]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])