In [3]:
print("Hello my name is Ario")

Hello my name is Ario


In [4]:
!nvidia-smi

Thu Aug 13 11:24:16 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
import torch
print(torch.__version__)

2.11.0+cu128


Creating Tensors

In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [10]:
# get tensor back as python int
scalar.item()

7

In [13]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [14]:
vector.ndim

1

In [15]:
vector.shape

torch.Size([2])

In [17]:
# matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim

2

In [21]:
# tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[10, 10, 320],
                        [83, 5, 64],
                        [49, 7, 34]]])
TENSOR

tensor([[[  1,   2,   3],
         [  3,   6,   9],
         [  2,   4,   5]],

        [[  1,   2,   3],
         [  4,   5,   6],
         [  7,   8,   9]],

        [[ 10,  10, 320],
         [ 83,   5,  64],
         [ 49,   7,  34]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([3, 3, 3])

In [24]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [25]:
TENSOR[1]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
TENSOR[2]

tensor([[ 10,  10, 320],
        [ 83,   5,  64],
        [ 49,   7,  34]])

In [27]:
TENSOR[0][0]

tensor([1, 2, 3])

In [28]:
TENSOR[2][1]

tensor([83,  5, 64])

### Random tensors
random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.


`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers
`

In [30]:
# create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5278, 0.1681, 0.9430, 0.9187],
        [0.1751, 0.0216, 0.9439, 0.5317],
        [0.5147, 0.6164, 0.1010, 0.9582]])

In [34]:
random_tensor.ndim

2

In [36]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [37]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
# Create tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
ones.dtype

torch.float32

In [43]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [45]:
# Use torch.range()
torch.range(0, 10)

/tmp/ipykernel_823/1840815090.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])