## PyTorch methods

## Basics

In [9]:
import torch
print(torch.__version__)


scalar = torch.tensor(7) # 0 dimensional tensor
print(f"scalar.item(): {scalar.item()}") # retrieving value as python int


vector = torch.tensor([7, 7]) # 1 dimensional tensor
print(f"\nvector.ndim: {vector.ndim}") # number of dimensions (1 in this case)
print(f"vector.shape: {vector.shape}") # the shape of our tensor (2 in this case)


MATRIX = torch.tensor([[7, 8], [9, 10]]) # 2x2 tensor
print(f"\nMATRIX.ndim: {MATRIX.ndim}") # 2 in this case


TENSOR = torch.arange(1, 11, 2) # from 1 to 11, steps of 2
print(f"\nTENSOR after arange(1, 11, 2): \n{TENSOR}\n")
TENSOR = torch.rand(3, 4) # 3x4 random tensor (uniform distribution between 0 and 1)
print(f"TENSOR after rand(3, 4): \n{TENSOR}\n")
TENSOR = torch.randn(3, 4) # 3x4 random tensor (bell-shaped normal distribution between -3 and 3 with mean of 0)
print(f"TENSOR after randn(3, 4): \n{TENSOR}\n")


print(f"TENSOR: \n{TENSOR}\n")
print(f"TENSOR.dtype: {TENSOR.dtype}")
print(f"TENSOR.shape: {TENSOR.shape}")
print(f"TENSOR.device: {TENSOR.device}")

2.11.0+cu128
scalar.item(): 7

vector.ndim: 1
vector.shape: torch.Size([2])

MATRIX.ndim: 2

TENSOR after arange(1, 11, 2): 
tensor([1, 3, 5, 7, 9])

TENSOR after rand(3, 4): 
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

TENSOR after randn(3, 4): 
tensor([[ 1.1103, -1.6898, -0.9890,  0.9580],
        [ 1.3221,  0.8172, -0.7658, -0.7506],
        [ 1.3525,  0.6863, -0.3278,  0.7950]])

TENSOR: 
tensor([[ 1.1103, -1.6898, -0.9890,  0.9580],
        [ 1.3221,  0.8172, -0.7658, -0.7506],
        [ 1.3525,  0.6863, -0.3278,  0.7950]])

TENSOR.dtype: torch.float32
TENSOR.shape: torch.Size([3, 4])
TENSOR.device: cpu


## Mathematical calculations

In [10]:
TENSOR = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"-------- TENSOR -------- \n{TENSOR}\n")
print(f"TENSOR + 10: \n{TENSOR + 10}\n")
print(f"TENSOR - 10: \n{TENSOR - 10}\n")
print(f"TENSOR * 10: \n{TENSOR * 10}\n")
# torch.mul() is a built-in function for multiplication (faster than "*")
print(f"torch.mul(TENSOR, 10): \n{torch.mul(TENSOR, 10)}\n")
print(f"torch.add(TENSOR, 10): \n{torch.add(TENSOR, 10)}")

-------- TENSOR -------- 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

TENSOR + 10: 
tensor([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

TENSOR - 10: 
tensor([[-9, -8, -7],
        [-6, -5, -4],
        [-3, -2, -1]])

TENSOR * 10: 
tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

torch.mul(TENSOR, 10): 
tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

torch.add(TENSOR, 10): 
tensor([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])


## Zeros and Ones

In [11]:
zeros = torch.zeros(size=(3, 3)) # 3x3 tensor with all values as 0
ones = torch.ones(size=(3, 3)) #3x3 tensor with all values as 1
print(f"ones.dtype: {ones.dtype}") # the datatype
# datatypes:
# single percision: float32 (default)
# half percision: float16
# double percision: float64

ones.dtype: torch.float32


## datatype

In [12]:

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # datatype: float32/float 16/...
                               device=None, # "cpu" or "cuda" (cuda: nvidia gpu)
                               requires_grad=False # whether or not to track gradients with this tensors operations
                               )
print(f"float_32_tensor.dtype: {float_32_tensor.dtype}")

float_16_tensor = float_32_tensor.type(torch.float16) # converting to float16
float_16_tensor = float_32_tensor.type(torch.half) # does the same thing
print(f"float_16_tensor.dtype: {float_16_tensor.dtype}")


float_32_tensor.dtype: torch.float32
float_16_tensor.dtype: torch.float16


## Matrices

In [13]:

# for matrix multiplication the inner and outer dimensions must match
print("-------- MATRICES --------")
matrix_1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
matrix_2 = torch.tensor([[4, 5, 6],[7, 8, 9]])
print(f"matrix_1: \n{matrix_1}\n")
print(f"matrix_2: \n{matrix_2}")
print(f"matrix_2.T (using transpose to manuplate the shape): \n{matrix_2.T}\n")

print(f"torch.matmul(matrix_1, matrix_2.T): \n{torch.matmul(matrix_1, matrix_2.T)}\n")
print(f"torch.matmul(matrix_2.T, matrix_1): \n{torch.matmul(matrix_2.T, matrix_1)}\n")
print("NOTE: The resulting matrix has the shape of the outer dimension\n")
print("torch.matmul(): Handles basically everything. can do: 2D, 3D, batched, broadcasting")
print("torch.mm(): stricter, can only do 2D, Marginally faster")
print("TENSOR @ TENSOR: literally just calls torch.matmul()")




-------- MATRICES --------
matrix_1: 
tensor([[1, 2, 3],
        [4, 5, 6]])

matrix_2: 
tensor([[4, 5, 6],
        [7, 8, 9]])
matrix_2.T (using transpose to manuplate the shape): 
tensor([[4, 7],
        [5, 8],
        [6, 9]])

torch.matmul(matrix_1, matrix_2.T): 
tensor([[ 32,  50],
        [ 77, 122]])

torch.matmul(matrix_2.T, matrix_1): 
tensor([[32, 43, 54],
        [37, 50, 63],
        [42, 57, 72]])

NOTE: The resulting matrix has the shape of the outer dimension

torch.matmul(): Handles basically everything. can do: 2D, 3D, batched, broadcasting
torch.mm(): stricter, can only do 2D, Marginally faster
TENSOR @ TENSOR: literally just calls torch.matmul()


## Min, Max, Mean, Sum

In [14]:
x = torch.arange(0, 100, 10)
print(f"x: {x}")
print(f"x.min OR torch.min(x): {x.min(), torch.min(x)}")
print(f"x.max OR torch.max(x): {x.max(), torch.max(x)}\n")

print("the mean() function works with float32 but our current x tensor is in int64. so we have to parse it.")
print(f"x.dtype: {x.dtype}")
print(f"x.type(torch.float32).mean() OR torch.mean(x.type(torch.float32)): {x.type(torch.float32).mean()}")

print(f"torch.sum(x) OR x.sum(): {torch.sum(x)}")

x: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
x.min OR torch.min(x): (tensor(0), tensor(0))
x.max OR torch.max(x): (tensor(90), tensor(90))

the mean() function works with float32 but our current x tensor is in int64. so we have to parse it.
x.dtype: torch.int64
x.type(torch.float32).mean() OR torch.mean(x.type(torch.float32)): 45.0
torch.sum(x) OR x.sum(): 450


## Position of Min and Max

In [15]:
print(f"x.argmin(): {x.argmin()}")
print(f"x[x.argmin()]: {x[x.argmin()]}")
print(f"x.argmax(): {x.argmax()}")
print(f"x[x.argmax()]: {x[x.argmax()]}")

x.argmin(): 0
x[x.argmin()]: 0
x.argmax(): 9
x[x.argmax()]: 90


# Reshaping, stacking, sqeezing, and unsqueezing tensors

## Reshaping

In [16]:
import torch
# reshape literally reshapes the tensor.
x = torch.arange(1., 13.)
print(f"x: {x}\nx.shape: {x.shape}\n\n")

x_reshaped = x.reshape(1, 12)
print("AFTER x.reshape(1, 12)")
print(f"x_reshaped: {x_reshaped}")
print(f"x_reshaped.shape: {x_reshaped.shape}")
print(f"x_reshaped.ndim: {x_reshaped.ndim}\n\n")

x_reshaped2 = x.reshape(3, 4)
print("AFTER x_reshape(3, 4)")
print(f"x_reshaped2: {x_reshaped2}")
print(f"x_reshaped2.shape: {x_reshaped2.shape}")
print(f"x_reshaped2.ndim: {x_reshaped2.ndim}")

x: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
x.shape: torch.Size([12])


AFTER x.reshape(1, 12)
x_reshaped: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
x_reshaped.shape: torch.Size([1, 12])
x_reshaped.ndim: 2


AFTER x_reshape(3, 4)
x_reshaped2: tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
x_reshaped2.shape: torch.Size([3, 4])
x_reshaped2.ndim: 2


## View (view of a tensor shares the same memory location as the tensor itself)

In [17]:
z = x.view(2, 6)
print(f"z.shape: {z.shape}\n")
z[:, 0] = 99 # from each dimension change the 0th index to 99
print(f"z after change on z:\n{z}\n")
print(f"x after change on z:\n{x}")

z.shape: torch.Size([2, 6])

z after change on z:
tensor([[99.,  2.,  3.,  4.,  5.,  6.],
        [99.,  8.,  9., 10., 11., 12.]])

x after change on z:
tensor([99.,  2.,  3.,  4.,  5.,  6., 99.,  8.,  9., 10., 11., 12.])


## Stacking (basically just stacking vertically or horizontally)

In [18]:
x_stacked = torch.stack([x, x, x, x], dim=0)
print(f"stacking 4 x tensors in dim=0:\n{x_stacked}\n")
x_stacked2 = torch.stack([x, x, x, x], dim=1)
print(f"stacking 4 x tensors in dim=1:\n{x_stacked2}")

stacking 4 x tensors in dim=0:
tensor([[99.,  2.,  3.,  4.,  5.,  6., 99.,  8.,  9., 10., 11., 12.],
        [99.,  2.,  3.,  4.,  5.,  6., 99.,  8.,  9., 10., 11., 12.],
        [99.,  2.,  3.,  4.,  5.,  6., 99.,  8.,  9., 10., 11., 12.],
        [99.,  2.,  3.,  4.,  5.,  6., 99.,  8.,  9., 10., 11., 12.]])

stacking 4 x tensors in dim=1:
tensor([[99., 99., 99., 99.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [99., 99., 99., 99.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])


## Squeeze & Unsqeeze (removing or adding dimensions)

In [19]:
x = torch.zeros(2, 1, 2, 1, 3, 5, 1)
print(f"x.size():                               {x.size()}")
y = torch.squeeze(x)
print(f"torch.squeeze(x).size():                {y.size()}           squeezes the \"useless\" dimensions (ones with size of 1)")
y = torch.squeeze(x, (1, 3, 6))
print(f"torch.squeeze(x, (1, 3, 6)).size():     {y.size()}           dimensions at indexes 1, 3, and 6 got \"squeezed\"\n")


x_unsqueezed = y.unsqueeze(dim=0)
print(f"y.unsqueeze(dim=0).size():              {x_unsqueezed.size()}")

x.size():                               torch.Size([2, 1, 2, 1, 3, 5, 1])
torch.squeeze(x).size():                torch.Size([2, 2, 3, 5])           squeezes the "useless" dimensions (ones with size of 1)
torch.squeeze(x, (1, 3, 6)).size():     torch.Size([2, 2, 3, 5])           dimensions at indexes 1, 3, and 6 got "squeezed"

y.unsqueeze(dim=0).size():              torch.Size([1, 2, 2, 3, 5])


# Permute (rearranges the dimensions)

In [20]:
z = torch.randn(2, 3, 5)
print(f"z = torch.randn(2, 3, 5).size():        {z.size()}")
z_permuted = torch.permute(z, (2, 0, 1))
print(f"torch.permute(z, (2, 0, 1)).size():     {z_permuted.size()}")

z = torch.randn(2, 3, 5).size():        torch.Size([2, 3, 5])
torch.permute(z, (2, 0, 1)).size():     torch.Size([5, 2, 3])


# PyTorch tensors & NumPy

In [21]:
import torch
import numpy as np

print("---- numpy to tensor ----")
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)        # numpy default dtype is float64 so the tensor takes that.
print(f"numpy array:                {array}")
print(f"tensor:                     {tensor}")
tensor2 = tensor.type(torch.float32)
print(f"tensor2.dtype:              {tensor2.dtype}\n")


print("---- tensor to numpy ----")
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(f"tensor: {tensor}")
print(f"numpy_tensor: {numpy_tensor}      AND     dtype={numpy_tensor.dtype}")

---- numpy to tensor ----
numpy array:                [1. 2. 3. 4. 5. 6. 7.]
tensor:                     tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
tensor2.dtype:              torch.float32

---- tensor to numpy ----
tensor: tensor([1., 1., 1., 1., 1., 1., 1.])
numpy_tensor: [1. 1. 1. 1. 1. 1. 1.]      AND     dtype=float32


# Reproducibility **(important)**

In [22]:
import torch

print("---- two random tensors ----")
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"random_tensor_A:\n{random_tensor_A}")
print(f"random_tensor_B:\n{random_tensor_B}")
print("Comparing the two:")
print(random_tensor_A == random_tensor_B)


print("\n\n---- setting random seed ----")
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) # <------------ HAS TO BE SET EACH TIME
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED) # <------------ HAS TO BE SET EACH TIME
random_tensor_D = torch.rand(3, 4)
print(f"random_tensor_C:\n{random_tensor_C}")
print(f"random_tensor_D:\n{random_tensor_D}")
print("Comparing the two:")
print(random_tensor_C == random_tensor_D)




---- two random tensors ----
random_tensor_A:
tensor([[0.1374, 0.2331, 0.9578, 0.3313],
        [0.3227, 0.0162, 0.2137, 0.6249],
        [0.4340, 0.1371, 0.5117, 0.1585]])
random_tensor_B:
tensor([[0.0758, 0.2247, 0.0624, 0.1816],
        [0.9998, 0.5944, 0.6541, 0.0337],
        [0.1716, 0.3336, 0.5782, 0.0600]])
Comparing the two:
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


---- setting random seed ----
random_tensor_C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
random_tensor_D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Comparing the two:
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# choosing between CPU and GPU automatically

In [23]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [24]:
tensor = torch.tensor([1, 2, 3], device="cpu")
print(f"tensor: {tensor}, {tensor.device}")
print("move tensor to GPU:")
tensor2 = tensor.to(device)
print(f"tensor2: {tensor2}")

tensor: tensor([1, 2, 3]), cpu
move tensor to GPU:
tensor2: tensor([1, 2, 3], device='cuda:0')
